//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTVL.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        //Kết nối server
        //        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        //        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        //        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TTVL-PC;Initial Catalog=TTVL_Schools;Persist Security Info=True;User " +
        //            "ID=sa;Password=P@ssword")]
        //        public string TTVL_SchoolsConnectionString {
        //            get {
        //                return ((string)(this["TTVL_SchoolsConnectionString"]));
        //            }
        //        }

        // Kết nối server Yes        //workstation id=MySchools.mssql.somee.com;packet size=4096;user id=thanhtungttvl_SQLLogin_1;pwd=n8fdnk7rs7;data source=MySchools.mssql.somee.com;persist security info=False;initial catalog=MySchools
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TTVL_SchoolsConnectionString
        {
            get
            {
                return ((string)(this["TTVL_SchoolsConnectionString"]));
            }
            set
            {
                this["TTVL_SchoolsConnectionString"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Springtime")]
        public string Skins
        {
            get
            {
                return ((string)(this["Skins"]));
            }
            set
            {
                this["Skins"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Conn
        {
            get
            {
                return ((string)(this["Conn"]));
            }
            set
            {
                this["Conn"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TaiKhoan
        {
            get
            {
                return ((string)(this["TaiKhoan"]));
            }
            set
            {
                this["TaiKhoan"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MatKhau
        {
            get
            {
                return ((string)(this["MatKhau"]));
            }
            set
            {
                this["MatKhau"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public bool Check
        {
            get
            {
                return ((bool)(this["Check"]));
            }
            set
            {
                this["Check"] = value;
            }
        }
    }
}
